language: node_js
node_js:
  - "4"
  - "5"
sudo: false
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - npm install
before_script:
  - sh -c "git log | head -12"
script:
  - npm run coverage
